<br>
<br>
<br>
<br>
<div class="row">
	<div class="col-12 col-sm-6 col-lg-6">
		<fieldset>
			<legend>Iniciar Sesion</legend>
			<?php
			if (isset($this->msje)) {
				echo '
				<div class="col-12">
					<center><span class="label label-warning">'.$this->msje.'</span></center>
				</div>
				';
			}
			?>
			<?php
				$form 	=	$this->form;
				$form->prepare();
				$form->setAttributes(array(
						'action'	=>	$this->url.'/fitness/index/recibe',
						'method'	=>	'post',
						'class'		=>	'form-horizontal'
					));
				$formLabel	=	$this->plugin('formLabel');
				echo $this->form()->openTag($form);
			?>
			<div class=" form-group">
				<?php
					$name = $form->get('txtUsuario');
					echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					echo $this->formElementErrors($name);
					echo $formLabel->closeTag();
				?>
				<div class="input-group">
					<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
					<?php echo $this->formInput($name); ?>
				</div>
			</div>
			<div class=" form-group">
				<?php
					$name = $form->get('txtClave');
					echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					echo $this->formElementErrors($name);
					echo $formLabel->closeTag();
				?>
				<div class="input-group">
					<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
					<?php echo $this->formInput($name); ?>
				</div>
			</div>
			<?php echo $this->formElement($form->get('btnIngreso')) ?>
			<?php echo $this->form()->closeTag() ?>
		</fieldset>
	</div>
</div>