<br />
<br />
<br />
<div class="row avatar">
	<div class="col-7">
	</div>
	<div class="col-5" id="avatarPer">
		<div class="col-3 filtro" >
			<?php $img=(file_exists('public/perfil/'.$this->id.'.jpg'))?$this->id.'.jpg':'logo.png'; 
			?>
			<img id="avatarPerFoto" src="<?php echo $this->basePath() . '/perfil/'.$img; ?>" width="70" height="75px">

			<!-- <img id="avatarPerFoto" src="<?php //echo $this->basePath() . '/perfil/2.png'; ?>" width="72" height="75px"> -->
			<svg width="0" height="0">
				<filter id="drop-shadow">
					<feGaussianBlur in ="[alpha-channel-of-input]" stdDeviation="[radius]"/>
					<feOffset dx ="[offset-x]" dy="[offset-y]" result="offsetblur"/>
					<feFlood flood-color ="[color]"/>
					<feComposite in2 ="offsetblur" operator="in"/>
					<feMerge>
						<feMergeNode/>
						<feMergeNode in ="[input-image]"/>
					</feMerge>
				</filter>
				<mask id ="mascara">
				</mask>
			</svg>
		</div>
		<div class="col-9" id="avatarPerInfo">
			<div class="row">
				<h4>Bienvenido: <b>Urrutia Santamaria, Erik</b><h4><sup>Coordinador</sup>
				<br />
				<sup>
					<a href="#">Configuracion</a>
					<a href="#">Salir</a>
				</sup>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<center>
		<a href="<?php echo $this->basePath() ?>/fitness/registros" class="btn btn-large btn-primary">
			<i class="icon-edit icon-6"> Registros</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/atencion" class="btn btn-large btn-primary">
			<i class="icon-group icon-6"> Atencion al Cliente</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/reportes" class="btn btn-large btn-primary">
			<i class="icon-group icon-6"> Reportes</i>
		</a>
	</center>
</div>