<br />
<div class="row">
	<center>
		<a href="<?php echo $this->basePath() ?>/fitness/registros" class="btn btn-large btn-primary">
			<i class="fa fa-edit"> Registros</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/atencion" class="btn btn-large btn-primary">
			<i class="fa fa-group"> Atencion al Cliente</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/reportes" class="btn btn-large btn-primary">
			<i class="fa fa-group"> Reportes</i>
		</a>
	</center>
</div>