<br>
<br>
<br>
<div class="container col-12">
	<div class="row">
	<center>
		<a href="<?php echo $this->basePath() ?>/fitness/registros" class="btn btn-large btn-primary">
			<i class="icon-edit icon-6"> Registros</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/atencion" class="btn btn-large btn-primary">
			<i class="icon-group icon-6"> Atencion al Cliente</i>
		</a>
		<a href="<?php echo $this->basePath() ?>/fitness/reportes" class="btn btn-large btn-primary">
			<i class="icon-group icon-6"> Reportes</i>
		</a>
	</center>
	</div>
</div>