<div class="row">
	<div class="span4">
		<div class="fondo">
		</div>
		<div class="hero-unit color2" id="BoxFrmCuenta">
			<?php
				$form 	=	$this->frmCuenta;
				$form->prepare();
				$form->setAttributes(array(
					// 'action'	=>	$this->url.'/fitness/registros/regsucursal',
					'method'	=>	'post',
					'id'		=>	'frmCuenta'
					));

				$formLabel	=	$this->plugin('formLabel');

				echo $this->form()->openTag($form);
			?>
			<fieldset>
				<legend><?php echo $this->titulo ?></legend>
				
				<div class="control-group">
					<?php
						$tipoCta = $form->get('cmbTipo');
					    echo $formLabel->openTag($tipoCta->getLabelAttributes() ) . $tipoCta->getLabel();
					    echo $formLabel->closeTag();
					    echo $this->formSelect($tipoCta);
					    echo $this->formElementErrors($tipoCta);
					?>
				</div>
				<div class="control-group">
					<?php
						$moneda = $form->get('cmbMoneda');
					    echo $formLabel->openTag($moneda->getLabelAttributes() ) . $moneda->getLabel();
					    echo $formLabel->closeTag();
					    echo $this->formSelect($moneda);
					    echo $this->formElementErrors($moneda);
					?>
				</div>

				<div class="control-group">
					<?php
					    $name = $form->get('txtBanco');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-prepend">
							<span class="add-on"><i class="icon-phone-sign icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<?php echo $this->formElement($form->get('btnRegCuenta')) ?>
				<?php echo $this->form()->closeTag() ?>
			</fieldset>
		</div>
	</div>



	<div class="span8">
		<div class="color5 hero-unit">
			<p id="dataCuenta"></p>
			<fieldset>
				<legend>dsada</legend>
			</fieldset>
			<table class="table table-bordered table-striped table-condensed" id="example">
			<!-- <caption>Resultados pa_listarPedido</caption> -->
			 	<thead>
					<tr>
						<!-- <th>ID</th> -->
						<th>Tipo de Cuenta</th>
						<th>Tipo de Moneda</th>
						<th>Banco</th>
						<th>Acciones</th>
						<!-- <th>Eliminar</th> -->
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
			<br>
			<a href="<?php echo $this->basePath() ?>/fitness/registros" id="btnEditar" class="btn btn-large btn-primary">
				<i class="icon-group"> Editar</i>
			</a>
			<a href="<?php echo $this->basePath() ?>/fitness/registros" id="btnEliminar" class="btn btn-large btn-primary">
				<i class="icon-group"> Eliminar</i>
			</a>
		</div>
	</div>
</div>

<div id="modalCuenta" class="modal hide fade zfgreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="tituloModal">Fitness House</h3>
  </div>
  <div class="modal-body">
    <p id="msjeModal">.</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cerrar</button>
  </div>
</div>