<br><br><br>
<div class='container'>
<center>
	<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'registros/sucursal' ?>">
		<div class='menu'>
			<i class="icon-building icon-5x"></i>
			<br/>
			Registrar Sucursal
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'registros/personal' ?>">
		<div class='menu'>
			<i class="icon-group icon-5x"></i>
			<br/>
			Personal
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'registros/empresa' ?>">
		<div class='menu'>
			<i class="icon-inbox icon-5x"></i>
			<br/>
			Empresa
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2" class="menu" href="<?php echo $this->url().'registros/servicio' ?>">
		<div class='menu'>
			<i class="icon-tag icon-5x"></i>
			<br/>
			Servicio Base
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'registros/plan' ?>">
		<div class='menu'>
			<i class="icon-tags icon-5x"></i>
			<br/>
			Plan
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'registros/promocion' ?>">
		<div class='menu'>
			<i class="icon-star icon-5x"></i>
			<br/>
			Promocion
		</div>
	</a>
</center>
</div>