<br>
<div class='container'>
<center>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/sucursal' ?>">
		<div>
			<i class="fa fa-building fa-5x"></i>
			<br/>
			Registrar Sucursal
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/personal' ?>">
		<div>
			<i class="fa fa-group fa-5x"></i>
			<br/>
			Personal
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/servicio' ?>">
		<div>
			<i class="fa fa-tag fa-5x"></i>
			<br/>
			Servicio Base
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/plan' ?>">
		<div>
			<i class="fa fa-tags fa-5x"></i>
			<br/>
			Plan
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/promocion' ?>">
		<div>
			<i class="fa fa-star fa-5x"></i>
			<br/>
			Promocion
		</div>
	</a>
	<a class="col-6 col-sm-6 col-lg-2 menu" href="<?php echo $this->url().'registros/empresa' ?>">
		<div>
			<i class="fa fa-suitcase fa-5x"></i>
			<br/>
			Empresa
		</div>
	</a>
</center>
</div>