<div class="row">
	<div class="col-12 col-sm-6 col-lg-6">
		
				<?php
					$form 	=	$this->frmPago;
					$form->prepare();
					$form->setAttributes(array(
						'method'	=>	'post',
						'id'		=>	'frmPago',
						//'class'		=>	'controls'
						));

					$formLabel	=	$this->plugin('formLabel');
					echo $this->form()->openTag($form);
				?>
			<fieldset>
				<legend >Registrar Pago</legend>
					<div class="row">
							
						<div class="form-group">
								<?php
								    $name = $form->get('txtDni');
								    echo $formLabel->openTag($name->getOption('label_attributes'));
								    echo $name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
							
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-barcode icono"></i></span>
										<?php echo $this->formInput($name); ?>
										<a class="btn" data-toogle="button" buttonType="primary" id="btnConsultar"><i class="icon-search icon"></i></a>
									<?php //echo $this->formElement($form->get('btnConsultar')) ?>
									</div>
								
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtCliente');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-user icono"></i></span>
										<?php echo $this->formInput($name); ?>
									</div>
								
							</div>
						</div>

						<div class="row">

							<div class="form-group">
								<?php
								    $name = $form->get('txtServicio');
									echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
									echo $this->formElementErrors($name);
									echo $formLabel->closeTag();
								?>
								
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-calendar icono"></i></span>
										<?php echo $this->formInput($name); ?>
									</div>
								
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtPago');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-home icono"></i></span>
										<?php echo $this->formInput($name); ?>
									</div>
								
							</div>
						</div>

						<div class="row">
							<div class="form-group">
								<?php
									$moneda = $form->get('cmbMoneda');
								    echo $formLabel->openTag($moneda->getLabelAttributes() ) . $moneda->getLabel();
								    echo $formLabel->closeTag();
								    echo $this->formSelect($moneda);
								    echo $this->formElementErrors($moneda);
								?>
							</div>
								<div class="form-group">
									<?php
										$moneda = $form->get('cmbPago');
									    echo $formLabel->openTag($moneda->getLabelAttributes() ) . $moneda->getLabel();
									    echo $formLabel->closeTag();
									    echo $this->formSelect($moneda);
									    echo $this->formElementErrors($moneda);
									?>
								</div>
						</div>
						<div class="row">
							<div class="form-group">
								<?php
									$moneda = $form->get('cmbConcepto');
								    echo $formLabel->openTag($moneda->getLabelAttributes() ) . $moneda->getLabel();
								    echo $formLabel->closeTag();
								    echo $this->formSelect($moneda);
								    echo $this->formElementErrors($moneda);
								?>
							</div>
								<div class="form-group">
									<?php
										$moneda = $form->get('cmbEstado');
									    echo $formLabel->openTag($moneda->getLabelAttributes() ) . $moneda->getLabel();
									    echo $formLabel->closeTag();
									    echo $this->formSelect($moneda);
									    echo $this->formElementErrors($moneda);
									?>
								</div>
						</div>
						<div class="row">
							<div class="form-group">
								<?php
								    $name = $form->get('dtpFechaReg');
									echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
									echo $this->formElementErrors($name);
									echo $formLabel->closeTag();
								?>
								
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-calendar icono"></i></span>
										<?php echo $this->formInput($name); ?>
									</div>
								
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('dtpFechaPago');
									echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
									echo $this->formElementErrors($name);
									echo $formLabel->closeTag();
								?>
								
									<div class="input-group">
										<span class="input-group-addon"><i class="icon-calendar icono"></i></span>
										<?php echo $this->formInput($name); ?>
									</div>
								
							</div>
						</div>						
												
							<div class="form-group">
								<?php
								    $name = $form->get('txtIdPer');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								 
								<?php echo $this->formInput($name); ?>
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtIdCli');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								 
								<?php echo $this->formInput($name); ?>
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtIdSer');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								 <?php echo $this->formInput($name); ?>
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtIdSuc');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								 
								<?php echo $this->formInput($name); ?>
							</div>
							<div class="form-group">
								<?php
								    $name = $form->get('txtIdCta');
								    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
								    echo $this->formElementErrors($name);
								    echo $formLabel->closeTag();
								?>
								 <?php echo $this->formInput($name); ?>
							</div>
							
					<?php echo $this->formElement($form->get('send')) ?>
					
					<?php echo $this->form()->closeTag() ?>
				</fieldset>
	</div>

</div>

<div id="modalPago" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal"></p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cerrar</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->