<div class="row">
<?php
	$form 	=	$this->frmPlan;
	$form->prepare();
	$form->setAttributes(array(
		// 'action'	=>	$this->url.'/fitness/registros/regsucursal',
		'method'	=>	'post',
		'id'		=>	'frmPlan'
		));
	$formLabel	=	$this->plugin('formLabel');
	echo $this->form()->openTag($form);
?>
<div class="accordion" id="accordion2">
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn-gym" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
		Aplicar Promocion a Plan o Servicio Existente.
      </a>
    </div>
    <div id="collapseOne" class="accordion-body collapse in">
      <div class="accordion-inner">
		<div class="row">
			<div class="form-group col-6">
					<?php
						$linea = $form->get('cmbPlanBase');
						echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
						echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-bookmark-o icono"></i></span>
						<?php
							echo $this->formSelect($linea);
							echo $this->formElementErrors($linea);
						?>
						<div class="input-group-btn">
							<a class="btn btn-default" data-toogle="button" buttonType="primary" id="btnBuscaPlan">
								<i class="fa fa-search icon"></i>
							</a>
						</div>
					</div>
				</div>
		</div>
      </div>
    </div>
  </div>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle btn-gym" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
		Crear Nuevo Plan con Promocion.
      </a>
    </div>
    <div id="collapseTwo" class="accordion-body collapse">
      <div class="accordion-inner">
        <div class="row">
			<div class='col-12' id="boxHorario">
					<fieldset>
						<legend>&nbsp;Promocion</legend>
		    			<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
								$linea = $form->get('cmbTipoPro');
							    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
							    echo $formLabel->closeTag();
							    echo $this->formSelect($linea);
							    echo $this->formElementErrors($linea);
							?>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('dtpFechaIni');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-calendar icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('dtpFechaFin');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-calendar icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('txtMontoPro');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-money icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>

						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('txtdiasPro');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('txtPorcentaje');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-star-half-o icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('txtEmpresaMin');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<div class="form-group col-12 col-sm-6 col-lg-3">
							<?php
							    $name = $form->get('txtEmpresaMax');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							 <div class="controls">
								<div class="input-group">
									<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
									<?php echo $this->formInput($name); ?>
								</div>
							</div>
						</div>
						<?php echo $this->formElement($form->get('btnRegPlan')) ?>
						<?php echo $this->formElement($form->get('btnCancelar')) ?>
					</fieldset>
			<br /><br />
			</div>
			<div class="col-12">
				<fieldset id="datosPlan">
					<legend>Datos del Plan</legend>
					<div class="row">
					</div>
					<div class="col-12 col-sm-4 col-lg-4">
						<!-- 1 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtNombre');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-bookmark-o icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<!-- 2 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtMonto');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-money icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<!-- 3 -->
						<div class="form-group" id="boxVigencia">
							<label class="control-label" for="Vigencia">Tipo Vigencia : </label>
							<div class="btn-group btn-group-justified" data-toggle="buttons" id="Vigencia">
								<label class="btn btn-gym btnVigencia">
									<input type="radio" class="btn btn-gym btnVigencia btn-medium active" id="btnVigencia0" >Dias
								</label>
								<label class="btn btn-gym btnVigencia">
									<input type="radio" class="btn btn-gym btnVigencia btn-medium" id="btnVigencia1">Semanas
								</label>
								<label class="btn btn-gym btnVigencia">
									<input type="radio" class="btn btn-gym btnVigencia btn-medium" id="btnVigencia2">Quincenal
								</label>
								<label class="btn btn-gym btnVigencia">
									<input type="radio" class="btn btn-gym btnVigencia btn-medium" id="btnVigencia3">Mensual
								</label>
							</div>
						</div>
						<!-- 4 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtDuracion');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-calendar-o icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-4 col-lg-4">
						<!-- 5 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtdiasCupon');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<!-- 6 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtfreezing');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<!-- 7 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtMontoIni');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-money icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<!-- 8 -->
						<div class="form-group">
							<?php
							    $name = $form->get('txtCuotaMax');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-sort-numeric-asc icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-4 col-lg-4">
						<!-- 9 -->
						<div class="form-group checkbox">
							<?php
								$condiciones = $form->get('chkLimite');
								echo $formLabel->openTag($condiciones->getLabelAttributes()) . $condiciones->getLabel();
								echo $this->formCheckbox($condiciones);
								echo $this->formElementErrors($condiciones);
								echo $formLabel->closeTag();
							?>
						</div>

						<!-- 10 -->
						<?php
							$lstSucursal = $form->get('lstSucursal');
							echo $formLabel->openTag() . $lstSucursal->getLabel();
							echo $formLabel->closeTag();
							echo $this->formSelect($lstSucursal);
							echo $this->formElementErrors($lstSucursal);
						?>
						<!-- 11 -->
						<?php
							$lstServicios = $form->get('lstServicios');
							echo $formLabel->openTag() . $lstServicios->getLabel();
							echo $formLabel->closeTag();
							echo $this->formSelect($lstServicios);
							echo $this->formElementErrors($lstServicios);
						?>
					</div>
					<div class="detalle">
						<!-- 12 -->
						<div class="form-group col-6">
							<?php
							    $name = $form->get('dtpFecha');
							    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
							    echo $this->formElementErrors($name);
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-calendar icono"></i></span>
								<?php echo $this->formInput($name); ?>
							</div>
						</div>
						<div class="form-group col-6">
							<?php
								$linea = $form->get('cmbTipoPlan');
								echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
								echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="fa fa-bookmark-o icono"></i></span>
								<?php
									echo $this->formSelect($linea);
									echo $this->formElementErrors($linea);
								?>
							</div>
						</div>
						<?php
							$name = $form->get('txtPersonal');
							$name->setAttribute('value', $this->per);
							echo $this->formInput($name);
						?>
					</div>
						<?php echo $this->formInput($form->get('txtPromocion')); ?>
						<?php echo $this->formInput($form->get('txtTipoDuracion')); ?>
						<?php echo $this->formInput($form->get('txtTipo')); ?>
						<?php echo $this->form()->closeTag() ?>
				</fieldset>
			</div>
			<?php echo $this->form()->closeTag() ?>
		</div>
      </div>
    </div>
  </div>
</div>
<div id="modalServicio" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal"></p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cerrar</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div id="modalAccion" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal">No se a especificado ningun horario! <br/> ¿Desea Continuar con el Resgistro del Servicio?</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-danger" id="btnRegistrar" aria-hidden="true">Si</a>
		<a class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">No</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->