<div class="row">
	<?php
		$form 	=	$this->frmPlan;
		$form->prepare();
		$form->setAttributes(array(
			// 'action'	=>	$this->url.'/fitness/registros/regsucursal',
			'method'	=>	'post',
			'id'		=>	'frmPlan'
			));
		$formLabel	=	$this->plugin('formLabel');
		echo $this->form()->openTag($form);
	?>
	<div class='col-12' id="boxHorario">
			<fieldset>
				<legend>Promocion</legend>
    			<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
						$linea = $form->get('cmbTipoPro');
					    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
					    echo $formLabel->closeTag();
					    echo $this->formSelect($linea);
					    echo $this->formElementErrors($linea);
					?>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('dtpFechaIni');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('dtpFechaFin');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('txtMontoPro');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>

				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('txtdiasPro');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('txtPorcentaje');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('txtEmpresaMin');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<div class="form-group col-12 col-sm-6 col-lg-3">
					<?php
					    $name = $form->get('txtEmpresaMax');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
					</div>
				</div>
				<?php echo $this->formElement($form->get('btnRegPlan')) ?>
				<a class="btn btn-default btn-block btn-large" id="btnCancelar">Nuevo</a>
			</fieldset>
	<br /><br />
	</div>
	<div class="col-12 col-sm-4 col-lg-4">
		<fieldset>
			<legend><?php echo $this->titulo ?></legend>
				<div class="form-group">
					<?php
					    $name = $form->get('txtNombre');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtMonto');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-money icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtdiasCupon');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-comments-alt icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtfreezing');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-th-large icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtMontoIni');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-money icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('dtpFecha');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-calendar icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
				<?php echo $this->formInput($form->get('txtPromocion')); ?>
				<?php echo $this->formInput($form->get('txtTipo')); ?>

				<div class="form-group">
					<?php
						$linea = $form->get('cmbEmpresa');
					    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-building icono"></i></span>
					<?php
						echo $this->formSelect($linea);
						echo $this->formElementErrors($linea);
					?>
				    </div>
				</div>
				<?php //echo $this->formInput($form->get('txtEstado')); ?>
				<!-- <div class="form-group"> -->
					<?php
					    // $name = $form->get('txtPersonal');
					    // echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    // echo $this->formElementErrors($name);
					    // echo $formLabel->closeTag();
					?>
					 <!-- <div class="controls">
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span> -->
							<?php //echo $this->formInput($name); ?>
				<!--</div>
					</div>
				</div> -->
				<?php
					$lstSucursal = $form->get('lstSucursal');
					echo $formLabel->openTag() . $lstSucursal->getLabel();
					echo $formLabel->closeTag();
					echo $this->formSelect($lstSucursal);
					echo $this->formElementErrors($lstSucursal);
				?>
				<?php
					$lstServicios = $form->get('lstServicios');
					echo $formLabel->openTag() . $lstServicios->getLabel();
					echo $formLabel->closeTag();
					echo $this->formSelect($lstServicios);
					echo $this->formElementErrors($lstServicios);
				?>
				<div class="form-group">
					<?php
					    $name = $form->get('txtPersonal');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<div class="input-group">
						<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
						<?php echo $this->formInput($name); ?>
					</div>
				</div>
    			<?php echo $this->formElement($form->get('btnRegPlan')) ?>
				<?php echo $this->form()->closeTag() ?>
				<a class="btn btn-default btn-block btn-large" id="btnCancelar">Nuevo</a>
			</fieldset>
	</div>
	<div class='col-12 col-sm-8 col-lg-8'>
		<fieldset class="Horario1">
		 	<legend>Programacion</legend>
				<div id='boxDia1'>
					<div class="row col-12">
						<div class="form-group col-5">
							<?php
								$linea = $form->get('cmbEncargado');
							    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="icon-user icono"></i></span>
								<?php
									echo $this->formSelect($linea);
									echo $this->formElementErrors($linea);
								?>
							</div>
						</div>
						<div class="col-1"></div>
						<div class="form-group col-5">
							<?php
								$linea = $form->get('cmbSucursal');
							    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
							    echo $formLabel->closeTag();
							?>
							<div class="input-group">
								<span class="input-group-addon"><i class="icon-building icono"></i></span>
								<?php
									echo $this->formSelect($linea);
									echo $this->formElementErrors($linea);
								?>
						    </div>
						</div>
					</div>
				</div>
				<table class='table table-condensed table-striped table-bordered table-hover'>
					<thead>
						<td></td>
						<td>Dia</td>
						<td>Incio</td>
						<td>Fin</td>
					</thead>
					<tbody>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Lunes' value="L" /></td>
							<td>Lunes</td>
							<td><input type="time" name="LunesIni" id="LunesIni" class='Lunes form-control input-sm' /></td>
							<td><input type="time" name="LunesFin" id="LunesFin" class='Lunes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Martes' value="M" /></td>
							<td>Martes</td>
							<td><input type="time" name="MartesIni" id="MartesIni" class='Martes form-control input-sm' /></td>
							<td><input type="time" name="MartesFin" id="MartesFin" class='Martes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Miercoles' value="W" /></td>
							<td>Miercoles</td>
							<td><input type="time" name="MiercolesIni" id="MiercolesIni" class='Miercoles form-control input-sm' /></td>
							<td><input type="time" name="MiercolesFin" id="MiercolesFin" class='Miercoles form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Jueves' value="J" /></td>
							<td>Jueves</td>
							<td><input type="time" name="JuevesIni" id="JuevesIni" class='Jueves form-control input-sm' /></td>
							<td><input type="time" name="JuevesFin" id="JuevesFin" class='Jueves form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Viernes' value="V" /></td>
							<td>Viernes</td>
							<td><input type="time" name="ViernesIni" id="ViernesIni" class='Viernes form-control input-sm' /></td>
							<td><input type="time" name="ViernesFin" id="ViernesFin" class='Viernes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Sabado' value="S" /></td>
							<td>Sabado</td>
							<td><input type="time" name="SabadoIni" id="SabadoIni" class='Sabado form-control input-sm' /></td>
							<td><input type="time" name="SabadoFin" id="SabadoFin" class='Sabado form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Domingo' value="D" /></td>
							<td>Domingo</td>
							<td><input type="time" name="DomingoIni" id="DomingoIni" class='Domingo form-control input-sm' /></td>
							<td><input type="time" name="DomingoFin" id="DomingoFin" class='Domingo form-control input-sm' /></td>
						</tr>
					</tbody>
				</table>
    	</fieldset>
		<a class="btn btn-block btn-primary btn-large" id="btnConfirmar">Confirmar</a>
		<br />
		<div class='col-12'>
			<fieldset>
			<legend>&nbsp;&nbsp;&nbsp;&nbsp;Horarios Agregados</legend>
			<div id="boxContenido">
			</div>
			</fieldset>
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>