<h1><?php echo $this->titulo ?></h1>
<div class="row hero-unit">
	<div class="span">
 <table class="table table-striped table-condensed table-bordered">
	<caption>Resultados desde modulo </caption>
 	<thead>
		<tr>
		<th>Codigo</th>
		<th>Nombre</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->datos as $dato) {
	?>
	<tr>
	<td><?php echo $dato['id_suc'] ?></td>
	<td><?php echo $dato['cod'] ?></td>
	</tr>
	<?php
}
?>
	</tbody>
</table>
</div>
</div>