<div class="row">
	<div class="col-12 col-sm-4 col-lg-4 accordion-group">
		<br />
		<div id="BoxfrmServicio">
			<?php
				$form 	=	$this->frmServicio;
				$form->prepare();
				$form->setAttributes(array(
					// 'action'	=>	$this->url.'/fitness/registros/regsucursal',
					'method'	=>	'post',
					'id'		=>	'frmServicio'
					));

				$formLabel	=	$this->plugin('formLabel');

				echo $this->form()->openTag($form);
			?>
			<fieldset>
				<legend>&nbsp;<?php echo $this->titulo ?></legend>
				<div class="form-group">
					<?php
					    $name = $form->get('txtNombre');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtMonto');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-money icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtdiasCupon');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-comments-alt icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtfreezing');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('txtMontoIni');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('dtpFecha');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<?php echo $this->formInput($form->get('txtPromocion')); ?>
				<?php echo $this->formInput($form->get('txtTipo')); ?>


				<div class="form-group">
					<?php
						$linea = $form->get('cmbEmpresa');
					    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
					    echo $formLabel->closeTag();
					?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
					<?php
						echo $this->formSelect($linea);
						echo $this->formElementErrors($linea);
					?>
					    </div>

				</div>
				<?php echo $this->formInput($form->get('txtEstado')); ?>

				<div class="form-group">
					<?php
					    $name = $form->get('txtPersonal');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-eye-open icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>

				</div>
				<?php
					$lstSucursal = $form->get('lstSucursal');
					echo $formLabel->openTag() . $lstSucursal->getLabel();
					echo $formLabel->closeTag();
					echo $this->formSelect($lstSucursal);
					echo $this->formElementErrors($lstSucursal);
				?>
				<br />
    			<?php echo $this->formElement($form->get('btnRegServicio')) ?>
				<?php echo $this->form()->closeTag() ?>
				<a class="btn btn-default btn-block" id="btnCancelar">Nuevo</a>
			</fieldset>
		</div>
		<br />
	</div>
	<div class='col-12 col-sm-6 col-lg-8'>
		<br />
		<fieldset class="Horario1 form-horizontal">
		 	<legend>&nbsp;Programacion</legend>
			<div id='boxDia1'>
				<div class="row col-12">
					<div class="form-group col-5">
						<?php
							$linea = $form->get('cmbEncargado');
						    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
						    echo $formLabel->closeTag();
						?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php
						    echo $this->formSelect($linea);
						    echo $this->formElementErrors($linea);
							?>
						</div>
					</div>
					<div class="col-1"></div>
					<div class="form-group col-5">
						<?php
							$linea = $form->get('cmbSucursal');
						    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
						    echo $formLabel->closeTag();
						?>
						<div class="input-group">
							<span class="input-group-addon"><i class="icon-home icono"></i></span>
							<?php
						    echo $this->formSelect($linea);
						    echo $this->formElementErrors($linea);
							?>
						</div>
					</div>
				<table class='table table-condensed table-striped table-bordered table-hover col-12'>
					<thead>
						<td></td>
						<td>Dia</td>
						<td>Incio</td>
						<td>Fin</td>
					</thead>
					<tbody>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Lunes' value="L" /></td>
							<td>Lunes</td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="LunesIni" id="LunesIni" class='Lunes form-control input-sm' /></td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="LunesFin" id="LunesFin" class='Lunes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Martes' value="M" /></td>
							<td>Martes</td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="MartesIni" id="MartesIni" class='Martes form-control input-sm' /></td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="MartesFin" id="MartesFin" class='Martes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Miercoles' value="W" /></td>
							<td>Miercoles</td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="MiercolesIni" id="MiercolesIni" class='Miercoles form-control input-sm' /></td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="MiercolesFin" id="MiercolesFin" class='Miercoles form-control input-sm' /></td>
							</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Jueves' value="J" /></td>
							<td>Jueves</td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="JuevesIni" id="JuevesIni" class='Jueves form-control input-sm' /></td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="JuevesFin" id="JuevesFin" class='Jueves form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Viernes' value="V" /></td>
							<td>Viernes</td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="ViernesIni" id="ViernesIni" class='Viernes form-control input-sm' /></td>
							<td><input type="time" min='06:00:00' max='22:00:00' name="ViernesFin" id="ViernesFin" class='Viernes form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Sabado' value="S" /></td>
							<td>Sabado</td>
							<td><input type="time" min='07:00' max='14:00' name="SabadoIni" id="SabadoIni" class='Sabado form-control input-sm' /></td>
							<td><input type="time" min='07:00' max='14:00' name="SabadoFin" id="SabadoFin" class='Sabado form-control input-sm' /></td>
						</tr>
						<tr>
							<td><input type="checkbox" name="dias[]" class='Domingo' value="D" /></td>
							<td>Domingo</td>
							<td><input type="time" min='09:00' max='13:00' name="DomingoIni" id="DomingoIni" class='Domingo form-control input-sm' /></td>
							<td><input type="time" min='09:00' max='13:00' name="DomingoFin" id="DomingoFin" class='Domingo form-control input-sm' /></td>
						</tr>
					</tbody>
				</table>
			</div>
    	</fieldset>
		<a class="btn btn-block btn-gym" id="btnConfirmar">Confirmar</a>
		<hr />
		<div class='col-12 accordion-group'>
			<br />
			<fieldset>
				<legend>&nbsp;Horarios Agregados</legend>
			</fieldset>
			<div id="boxContenido">
			</div>
			<br />
		</div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<div id="modalServicio" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal"></p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cerrar</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<div id="modalAccion" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal">No se a especificado ningun horario! <br/> ¿Desea Continuar con el Resgistro del Servicio?</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-danger" id="btnRegistrar" aria-hidden="true">Si</a>
		<a class="btn btn-inverse" data-dismiss="modal" aria-hidden="true">No</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->