<?php echo $this->doctype(); ?>
<?php
	$children 	=	$this->viewModel()->getCurrent()->getChildren();
	$variables	=	$children[0];
	$titulo		=	$children[0]->getTemplate();
	$titulo		=	explode("/", $titulo);
	$titulo		=	$titulo[count($titulo)-1];
	// var_dump($titulo[count($titulo)-1]);
?>
<html lang="es">
	<head>
		<meta charset ="utf-8">
		<?php echo $this->headTitle('Fitness House || '. $titulo)->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width =device-width, initial-scale=1.0') ?>

		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
						->prependStylesheet($this->basePath() . '/css/font-awesome-ie7.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
						->prependStylesheet($this->basePath() . '/css/jquery.dataTables.css')
						->prependStylesheet($this->basePath() . '/css/indice.css')
						?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
										// ->prependFile($this->basePath() . '/js/bootstrap.js')
										->appendFile($this->basePath() . '/js/pace.min.js')
										->prependFile($this->basePath() . '/js/bootstrap.min.js')
										->prependFile($this->basePath() . '/js/jquery.min.js')
										->appendFile($this->basePath() . '/js/validarcampo.js')
										->appendFile($this->basePath() . '/js/jquery.validate.js')
										->appendFile($this->basePath() . '/js/jquery.dataTables.js')
										->appendFile($this->basePath() . '/js/acciones.js')
										?>

	</head>
	<body>
		<div class ="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
			<div class ="container">
				<button class ="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
					<span class ="icon-bar"></span>
					<span class ="icon-bar"></span>
					<span class ="icon-bar"></span>
				</button>
				<a href ="<?php echo $this->url('home') ?>" class="navbar-brand"></a>
				<!-- <a class ="brand" href="<?php //echo $this->url() ?>"></a> -->
				<div class ="nav-collapse collapse bs-navbar-collapse">
					<ul class ="nav navbar-nav">
						<li>
							<a href ="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
						<li>
					</ul>
				</div>
			</div>
		</div>
		<br /><br /><br />
		<div class ="container">
			<div class ="row">
				<div class ="col-12 col-sm-12 col-lg-7">
				</div>
				<div class ="col-12 col-sm-12 col-lg-5" id="avatarPer">
					<?php
						$children	=	$this->viewModel()->getCurrent()->getChildren();
						$variables	=	$children[0];
					?>
					<div class ="col-4 col-sm-4 col-lg-3 filtro" >
						<?php $img =(file_exists('public/perfil/'.$variables->id.'.jpg'))?$variables->id.'.jpg':'logo.png';
                        ?>
						<img id ="avatarPerFoto" src="<?php echo $this->basePath() . '/perfil/'.$img; ?>" width="70" height="75px">
						<svg width ="0" height="0">
							<filter id ="drop-shadow">
								<feGaussianBlur in   ="[alpha-channel-of-input]" stdDeviation="[radius]"/>
								<feOffset dx         ="[offset-x]" dy="[offset-y]" result="offsetblur"/>
								<feFlood flood-color ="[color]"/>
								<feComposite in2     ="offsetblur" operator="in"/>
								<feMerge>
									<feMergeNode/>
									<feMergeNode in ="[input-image]"/>
								</feMerge>
							</filter>
							<mask id ="mascara">
							</mask>
						</svg>
					</div>
					<div class ="col-8 col-sm-8 col-lg-9" id="avatarPerInfo">
						<div class ="row">
							<h4>Bienvenido: <b><?php echo $variables->nombre ; ?></b><h4><sup><small>Coordinador</small></sup>
							<br />
							<sup>
								<a href ="sdsad">Configuracion</a>
								<a href ="<?php echo $this->basePath() . '/fitness/index/logoutper'; ?>">Salir</a>
							</sup>
						</div>
					</div>
				</div>
			</div>
			<div class ="row">
				<ul class ="breadcrumb">
					<li><a href ="<?php echo $this->url().'atencion/socio' ?>"><i class="fa fa-user"></i> Registrar Socio</a></li>
					<span class ="divider">&nbsp; | &nbsp;</span>
					<li><a href ="<?php echo $this->url().'atencion/inscripcion' ?>"><i class="fa fa-paste"></i> Registrar Inscripcion</a></li>
					<span class ="divider">&nbsp; | &nbsp;</span>
					<li><a href ="<?php echo $this->url().'atencion/asistencia' ?>"><i class="fa fa-stack-overflow"></i> Asistencia</a></li>
					<span class ="divider">&nbsp; | &nbsp;</span>
					<li><a href ="<?php echo $this->url().'atencion/pago' ?>"><i class="fa fa-money"></i> Pago</a></li>
					<span class ="divider">&nbsp; | &nbsp;</span>
					<li><a href ="<?php// echo $this->url().'atencion/freezing' ?>"><i class="fa fa-th-large"></i> Freezing</a></li>
					<span class ="divider">&nbsp; | &nbsp;</span>
					<li><a href ="<?php echo $this->url().'atencion/empresa' ?>"><i class="fa fa-suitcase"></i> Empresa</a></li>
				</ul>
			</div>
		</div>
		<div class ="container">
			<?php echo $this->content; ?>
			<hr>
			<footer>
				<p>Desarrollado por: Conectados</p>
			</footer>
		</div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
	</body>
</html>
