<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fitness House || '. $this->translate('Registros'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome-ie7.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.dataTables.css')
                        ->prependStylesheet($this->basePath() . '/css/indice.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      // ->prependFile($this->basePath() . '/js/bootstrap.js')
                                      ->appendFile($this->basePath() . '/js/pace.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->appendFile($this->basePath() . '/js/validarcampo.js')
                                      ->appendFile($this->basePath() . '/js/jquery.validate.js')
                                      ->appendFile($this->basePath() . '/js/jquery.dataTables.js')
                                      ->appendFile($this->basePath() . '/js/acciones.js')
                                       ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
          <div class="container">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="<?php echo $this->url('home') ?>" class="navbar-brand"></a>
                <!-- <a class="brand" href="<?php echo $this->url() ?>"></a> -->
            <div class="nav-collapse collapse bs-navbar-collapse">
              <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li>
              </ul>
            </div>
          </div>
        </div>
        <br /><br /><br /><br />
        <div class="container">
            <div class="row">
                <ul class="breadcrumb">
                    <li><a href="<?php echo $this->url().'atencion/socio' ?>"><i class="icon-user"></i> Registrar Socio</a></li>
                    <span class="divider">&nbsp; | &nbsp;</span>
                    <li><a href="<?php echo $this->url().'atencion/inscripcion' ?>"><i class="icon-paste"></i> Registrar Inscripcion</a></li>
                    <span class="divider">&nbsp; | &nbsp;</span>
                    <li><a href="<?php echo $this->url().'atencion/asistencia' ?>"><i class="icon-stackexchange"></i> Asistencia</a></li>
                    <span class="divider">&nbsp; | &nbsp;</span>
                    <li><a href="<?php echo $this->url().'atencion/pago' ?>"><i class="icon-money"></i> Pago</a></li>
                    <span class="divider">&nbsp; | &nbsp;</span>
                    <li><a href="<?php echo $this->url().'atencion/freezing' ?>"><i class="icon-th-large"></i> Freezing</a></li>
                    <span class="divider">&nbsp; | &nbsp;</span>
                    <li><a href="<?php echo $this->url().'atencion/empresa' ?>"><i class="icon-building"></i> Empresa</a></li>
                </ul>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Desarrollado por: Conectados</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
