<?php echo $this->doctype(); ?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Fitness House || '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        // ->prependStylesheet($this->basePath() . '/css/font-awesome-ie7.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        // ->prependStylesheet($this->basePath() . '/css/bootstrap.css') 
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/indice.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      // ->prependFile($this->basePath() . '/js/bootstrap.js')
                                      ->appendFile($this->basePath() . '/js/pace.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      ->appendFile($this->basePath() . '/js/jquery.validate.js')
                                      ->appendFile($this->basePath() . '/js/validarcampo.js')
                                      ->appendFile($this->basePath() . '/js/acciones.js')
                                       ?>
    </head>
    <body>
        <div class="pace-activity"></div>
        <div class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
          <div class="container">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="./" class="navbar-brand"></a>
            <div class="nav-collapse collapse bs-navbar-collapse">
              <ul class="nav navbar-nav">
                <li>
                    <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Desarrollado por: Conectados</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
