<br><br><br>
<div class='row'>
<center>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/socio' ?>">
    <div class='menu'>
        <i class="icon-user icon-5x"></i>
        <br />
        Registrar Socio
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/inscripcion' ?>">
    <div class='menu'>
        <i class="icon-paste icon-5x"></i>
        <br />
        Registrar Inscripcion
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/asistencia' ?>">
    <div class='menu'>
        <i class="icon-stackexchange icon-5x"></i>
        <br />
        Asistencia
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/pago' ?>">
    <div class='menu'>
        <i class="icon-money icon-5x"></i>
        <br />
        Pago
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/freezing' ?>">
    <div class='menu'>
        <i class="icon-th-large icon-5x"></i>
        <br />
        Freezing
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/empresa' ?>">
    <div class='menu'>
        <i class="icon-building icon-5x"></i>
        <br />
        Empresa
    </div>
</a>
</center>
</div>