<br>
<div class='row'>
<center>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/socio' ?>">
    <div class='menu'>
        <i class="fa fa-user fa-5x"></i>
        <br />
        Registrar Socio
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/inscripcion' ?>">
    <div class='menu'>
        <i class="fa fa-paste fa-5x"></i>
        <br />
        Registrar Inscripcion
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/asistencia' ?>">
    <div class='menu'>
        <i class="fa fa-stack-overflow fa-5x"></i>
        <br />
        Asistencia
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/pago' ?>">
    <div class='menu'>
        <i class="fa fa-money fa-5x"></i>
        <br />
        Pago
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/freezing' ?>">
    <div class='menu'>
        <i class="fa fa-th-large fa-5x"></i>
        <br />
        Freezing
    </div>
</a>
<a class="col-6 col-sm-6 col-lg-2" href="<?php echo $this->url().'atencion/empresa' ?>">
    <div class='menu'>
        <i class="fa fa-suitcase fa-5x"></i>
        <br />
        Empresa
    </div>
</a>
</center>
</div>