<div class="row">
	<div class="col-12 col-sm-6 col-lg-6">
			<fieldset>
				<legend>Lista de Cliente</legend>
			</fieldset>
			<table class="table table-bordered table-striped table-condensed" id="example">
				<caption id="tablaTitulo"></caption>
			 	<thead>
					<tr>
						<th><i class="fa fa-check-square-o fa-lg"></i></th>
						<th>Nombre de Socio</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
			<br>
				<div id="barra" class="progress progress-info progress-striped active">
					<div class="bar" style="width:100%"></div>
				</div>
			<div class="form-group form-inline" data-toggle="buttons-radio" id="boxEstados">
			</div>
	</div>
	<div class="col-12 col-sm-6 col-lg-6">
			<?php
				$form 	=	$this->frmInscripcion;
				$form->prepare();
				$form->setAttributes(array(
					// 'action'	=>	$this->url.'/fitness/registros/regsucursal',
					'method'	=>	'post',
					'id'		=>	'frmInscripcion'
					));

				$formLabel	=	$this->plugin('formLabel');

				echo $this->form()->openTag($form);
			?>
			<fieldset>
				<legend><?php echo $this->titulo ?></legend>
				<div class="form-group">
					<?php
						$linea = $form->get('cmbServicio');
						echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
						echo $formLabel->closeTag();
					?>
					<!-- <div class="controls"> -->
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-tags icono"></i></span>
						<?php
							echo $this->formSelect($linea);
							echo $this->formElementErrors($linea);
						?>
					</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('dtpFechaIni');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					<!--  <div class="controls"> -->
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-calendar icono"></i></span>
							<?php
								$name->setAttribute('value', date("Y-m-d"));
								echo $this->formInput($name);
							?>
						</div>
				</div>
				<div class="form-group">
					<?php
					    $name = $form->get('dtpFechaFin');
					    echo $formLabel->openTag($name->getOption('label_attributes')).$name->getOption('label');
					    echo $this->formElementErrors($name);
					    echo $formLabel->closeTag();
					?>
					 <!-- <div class="controls"> -->
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-calendar icono"></i></span>
							<?php echo $this->formInput($name); ?>
						</div>
				</div>
				<div class="form-group">
					<?php
						$linea = $form->get('cmbTipoInscripcion');
					    echo $formLabel->openTag($linea->getLabelAttributes() ) . $linea->getLabel();
					    echo $formLabel->closeTag();
					?>
					<!-- <div class="controls"> -->
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-check icono"></i></span>
					<?php
						echo $this->formSelect($linea);
						echo $this->formElementErrors($linea);
					?>
					    </div>
				</div>
				<?php
					$name = $form->get('txtPersonal');
					$name->setAttribute('value', $this->per);
					echo $this->formInput($name);
				?>
				<!-- <input type="hidden" name="txtId" id="txtId" value="" />
				<input type="hidden" name="txtEstado" id="txtEstado" value="" /> -->
				<?php echo $this->formElement($form->get('btnRegInscripcion')) ?>
				<?php echo $this->form()->closeTag() ?>
				<button class="btn btn-default btn-block btn-large" id="btnCancelar">Nuevo</button>
			</fieldset>
	</div>
</div>
<div id="modalIns" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body">
        <p id="msjeModal"></p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default" data-dismiss="modal">Cerrar</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->