<h1><?php echo $this->titulo ?></h1>
 <table class="table table-bordered table-striped table-condensed">
	<caption>Resultados desde modulo </caption>
 	<thead>
		<tr>
		<th>ID</th>
		<th>Nombre</th>
		<th>Area</th>
		</tr>
	</thead>
	<tbody>
	<tr>
	<td><?php echo $this->datos['id_per'] ?></td>
	<td><?php echo $this->datos['nombre_per'] ?></td>
	<td><?php echo $this->datos['area_per'] ?></td>
	</tr>
	</tbody>
</table>
<br>
<a href="<?php echo $this->basePath() ?>/fitness/formulario/tabla"><i class="icon-hand-left"> </i> ver</a>